apiVersion: batch/v1
kind: Job
metadata:
  name: routinename
spec:
  template:
    spec:
      containers:
      - name: routinename
        image: 192.168.101.63:5000/imagename
        command: ["wrapper.py", params]
      restartPolicy: Never
  backoffLimit: 4
