apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: detection
  name: detection
spec:
  selector:
    matchLabels:
      io.kompose.service: detection
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: detection
    spec:
      hostAliases:
        - ip: monitornode
          hostnames:
            - "monitornode.eqos"
      containers:
      - image: registry:5000/anomalies-in-performance
        name: detection
        resources: {}
      restartPolicy: Always
status: {}
