apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  selector:
    matchLabels:
      io.kompose.service: producer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: producer
    spec:
      containers:
      - image: registry:5000/producer
        name: producer
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: producer-claim0
      restartPolicy: Always
      volumes:
      - name: producer-claim0
        hostPath:
          path: /var/run/docker.sock
      nodeSelector:
        type: internalService
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "internalService"
          effect: "NoSchedule"
status: {}
