apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: shinyproxy
  name: shinyproxy
spec:
  selector:
    matchLabels:
      io.kompose.service: shinyproxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: shinyproxy
    spec:
      containers:
      - image: registry:5000/shinyproxy
        name: shinyproxy
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
